server:
  port: 9999
  host: 0.0.0.0
xxljob:
  admin_addresses:
    - 'http://localhost:8080/xxl-job-admin'
  app_name: go-executor
  access_token: ''
  log_path: ./logs
  log_retention_days: 7
executor:
  ip: localhost
  port: 9999
  server_id: server-001
database:
  default:
    host: localhost
    port: 3306
    username: root
    password: root
    database: xxljob_executor
    charset: utf8mb4
  business:
    host: localhost
    port: 3306
    username: root
    password: root
    database: xxljob_executor
    charset: utf8mb4
queue:
  enable: false  # 原有队列系统已被Asynq完全替换
  config_sync_interval: 10

redis:
  addr: localhost:6379
  password: ""
  db: 0

asynq:
  enable: true  # 默认启用Asynq
  concurrency: 20
  queues:
    critical: 6
    default: 3
    low: 1